- tests/testsuite.py
- xmlrunner/result.py
The ``addSubTest`` method is called even if no error is encountered during a subtest. In this case, the error is ``None``, and a ``TypeError`` exception is raised when the error is then converted to string.
> Fix for issue #85

- tox.ini
see https://bitbucket.org/ned/coveragepy/issues/419/nosource-no-source-for-code-path-to-c
> fix coverage bug with 4.0

- tests/testsuite.py
- xmlrunner/result.py
Without the _exc_info_to_string redefinition, test_xmlrunner_non_ascii_failures crashes on python2.7
> Fix crashes for on-ascii failures

- tests/testsuite.py
- xmlrunner/result.py
sys.stdout and sys.sterr may not necessarily be StringIO
yet. We should catch AttributeError when trying to call
getvalue() on them.
Fixes: #83
> Fix 'getvalue' AttributeError when test fails during __call__

- tox.ini
Issue was fixed in coverage:
https://bitbucket.org/ned/coveragepy/issues/419/nosource-no-source-for-code-path-to-c
> Remove pinned version for coverage.

- tests/django_test.py
- tox.ini
- xmlrunner/extra/djangotestrunner.py
and minor cleanup in a test file.
> Update Django testing to use the currently supported versions.

- .travis.yml
- README.md
- tox.ini
The intent is that if code coverage report are combined, then
parallelizing with tox-travis may make sense.
Using both tools as I want to see which one is better.
> Use codecov and coveralls.

- tests/builder_test.py
- tests/django_example/app/admin.py
- tests/django_example/app/models.py
- tests/django_example/app/tests.py
- tests/django_example/app/views.py
- tests/django_example/app2/admin.py
- tests/django_example/app2/models.py
- tests/django_example/app2/tests.py
- tests/django_example/app2/views.py
- tests/django_test.py
- tests/testsuite.py
> pep8 / flake8 for test code.

- tests/django_example/example/settings.py
- tests/django_example/example/urls.py
- tests/django_example/example/wsgi.py
- tests/django_example/manage.py
- tests/django_test.py
- xmlrunner/extra/djangotestrunner.py
> Add more tests for the django test runner.

- tests/testsuite.py
- tests/vendor/jenkins/xunit-plugin/junit-10.xsd
- tox.ini
- xmlrunner/runner.py
- copyright notice left intact,
- vendored file in path that points out to jenkins xunit-plugin.
see also:
http://stackoverflow.com/questions/4922867/junit-xml-format-specification-that-hudson-supports
> validate against jenkins/xunit-plugin junit-10.xsd

- xmlrunner/result.py
You can't use type(x) in six.string_types.
You need to do isinstance(x, six.string_types)
> Fix the check that the output stream is a string

- tests/testsuite.py
- xmlrunner/result.py
> garbage collect test reference.

- tests/django_test.py
- xmlrunner/extra/djangotestrunner.py
Using TEST_OUTPUT_FILE_NAME with Django does not create intermediate folders specified in TEST_OUTPUT_DIR
Now it creates intermediate folders if they don't exist. Includes tests.
Fixes #146
> Fixes #146

- tests/django_test.py
- tox.ini
- xmlrunner/extra/djangotestrunner.py
1. `xmlrunner.XMLTestRunner` was hardcoded into `xmlrunner.extra.djangotestrunner.XMLTestRunner`. Now it's overridable attribute of `xmlrunner.extra.djangotestrunner.XMLTestRunner`
2. kwargs for `xmlrunner.XMLTestRunner` is now generated in separate `get_test_runner_kwargs` method. It's made as in Django 1.11 but will work in Django 1.8 as well. Just follow naming convention. This was done mostly for code cleanup and separation.
3. Test for patch functionality added. It fails in pre-patch version and passes now. For this `mock` library was added in tox dependencies, hope it's ok.
4. Comments added across touched code.
> Ability to define custom test_runner for Django test runner

- tests/builder_test.py
- xmlrunner/builder.py
- xmlrunner/result.py
To monitor when tests have last run, we read the timestamp attribute from JUnit-XML files. It would be nice if XML generated by XMLRunner included this timestamp attribute. 
This pull request adds timestamps to testsuites and testcases in the XML output. The timestamp attributes are ISO8601 as specified by the JUnit DTD included in the XMLRunner sources.
> Add an ISO-8601 timestamp to every testsuite and testcase in the XML-report

- xmlrunner/result.py
If the reason for skipping a test is an empty string, unittext-xml-reporting throws the following confusing exception. By checking that `err` is not `None` instead of just truthy adds support for empty reasons.
```
@unittest.skip('')
def test_something(...):
pass
```
```
...
File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/xmlrunner/runner.py", line 112, in run
result.generate_reports(self)
File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/xmlrunner/result.py", line 486, in generate_reports
suite_name, tests, doc, parentElement, self.properties
File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/xmlrunner/result.py", line 367, in _report_testsuite
_XMLTestResult._report_testcase(test, testsuite, xml_document) …
```
> support empty skip reason

- tests/testsuite.py
- xmlrunner/result.py
- xmlrunner/runner.py
The current implementation uses the unittest's `--buffer` option to capture stdout / stderr outputs from tests that is used in XML reports.
This results to suppress real-time console outputs from tests. It is often inconvenient.
This change introduces own buffering mechanism instead of the unittests's `--buffer` option.
> Use own buffering mechanism to capture stdout / stderr for XML reports

- tests/testsuite.py
- xmlrunner/runner.py
Replaces #140.
`XMLTestRunner` doesn't receive options like `-b` via unittest.TestProgram in python3.
This is caused for this implementation in `unittest` in python3: https://github.com/python/cpython/blob/v3.4.8/Lib/unittest/main.py#L234
`XMLTestRunner.__init__` should be compatible with `TestTestRunner.__init__`.
> Make compatible with unittest.TestProgram in python3

- tests/testsuite.py
- xmlrunner/__main__.py
- xmlrunner/runner.py
I tested with Python 2.7, 3.5 and 3.7, and at least --buffer works
everywhere. I was also missing a way to specify the output directory,
so I added the ability to do so.
This fixes #143 and closes #144.
(Please note that the change doesn't affect Python 2.7 as it uses a different approach to parsing arguments.)
> runner: reinstate all unittest arguments; add --output

- xmlrunner/result.py
freezegun is simple package frequently used in tests to stop the
clock. When active on a class, xmlrunner reports that all its tests took
zero seconds, which is obviously incorrect. To easily bypass this
without making the code aware of freezegun, we import `time.time()`
by value.
> bypass freezegun if installed

- tests/testsuite.py
- xmlrunner/result.py
Deals with https://github.com/xmlrunner/unittest-xml-reporting/commit/4890cd7ca3ccfcd8fc881f0cdd1d257efe5f5e5f#r32781252
> Correctly handle partial test methods in startTest.

- tests/testsuite.py
- xmlrunner/result.py
This PR adjust expected failures to be reported as skips, includes output in successful tests and makes the verbose output more consistent with `unittest`.
> Include output in passing tests; fix expected failures; adjust verbose output

- tests/testsuite.py
- xmlrunner/result.py
When `xmlrunner.XMLTestRunner` is run in buffered mode,
`sys.stdout` points to StringIO instance. It has `encoding`
attribute, but it is set to `None` which causes a crash during
the test run in Python 2:
Traceback (most recent call last):
File "/home/miika/apps/unittest-xml-reporting/tests/testsuite.py", line 376, in test_xmlrunner_non_ascii_failures_buffered_output
self._xmlrunner_non_ascii_failures(buffer=True)
File "/home/miika/apps/unittest-xml-reporting/tests/testsuite.py", line 398, in _xmlrunner_non_ascii_failures
runner.run(suite)
File "/home/miika/apps/unittest-xml-reporting/xmlrunner/runner.py", line 70, in run
test(result)
File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
return self.run(*args, **kwds)
File "/usr/lib/python2.7/unittest/suite.py", line 108, in …
> Fix crash when exceptions contain unicode in buffered output

- tests/django_example/app/tests.py
- tests/django_test.py
- xmlrunner/result.py
These comments could for instance be retrieved by XSLT to add
description to test title.
> xmlrunner: Expose python docstrings as comments in the XML result file

- tests/testsuite.py
- xmlrunner/result.py
> [result] fix subtest referencing objects

- xmlrunner/result.py
This PR removes the empty stdout/stderr in XML test report output.
Output before:
```
<testcase classname="MyTestClass" name="test_my_test_name" time="0.000" timestamp="2020-04-12T16:01:18" file="test_the_xml_output.py" line="61">
<system-out><![CDATA[]]></system-out>
<system-err><![CDATA[]]></system-err>
</testcase>
```
Output now:
```
<testcase classname="MyTestClass" name="test_my_test_name" time="0.000" timestamp="2020-04-12T16:01:18" file="test_the_xml_output.py" line="61"/>
```
> Avoid including empty system-out and system-err when reporting testcases

- xmlrunner/builder.py
- xmlrunner/runner.py
- `time.time()` is the system time. "it's great" (tm)
however it is not reliable for measuring time spent.
it gives you the "current" time, but oh... time can move backwards
(thanks NTP).
- `time.monotonic()` is a monotonic time source. "it's great" (tm)
it only goes forward, making measurements a peach.
however it cannot be used as a reference point.
> make time measurements monotonic

- tests/testsuite.py
- xmlrunner/runner.py
I want to record test results without a datetime suffix. 
Because I need to send test results as the same name to use CircleCi's test in parallel (https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-by-timing-data)
However, the xmlrunner adds a date-time suffix to a test suite automatically. Although there are the same test cases, the CircleCI realizes different test cases.
So I add an outsuffix option to control a suffix from the command.
e.g) 
```
xmlrunner --output ./test-results/  --outsuffix="" tests/**/test_*.py
$ xmlrunner -h
usage: xmlrunner [-h] [-o DIR | --output-file FILENAME] [--outsuffix STRING]
optional arguments:
-h, --help            show this help message and exit
-o DIR, --output DIR  Directory for storing XML reports ('.' default)
--output-file FILENAME …
```
> Add outsuffix option

- tests/testsuite.py
- xmlrunner/result.py
- xmlrunner/unittest.py
See https://github.com/python/cpython/commit/b0a6ede3d0bd6fa4ffe413ab4dfc1059201df25b.
> Don't use aliases removed in Python 3.11.
